doctrine:
    dbal:
        types:
            uuid: 'App\Infrastructure\Persistence\Doctrine\DoctrineIdType'
            uuid_user: 'App\Infrastructure\Persistence\Doctrine\DoctrineUserIdType'
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_mapping: true
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: 'doctrine.orm.naming_strategy.underscore_number_aware'
        mappings:
            App\Domain\Category:
                dir: '%kernel.project_dir%/src/Domain/Category'
                is_bundle: false
                prefix: App\Domain\Category
                alias: AppDomainCategory
            App\Domain\Wallet:
                dir: '%kernel.project_dir%/src/Domain/Wallet'
                is_bundle: false
                prefix: App\Domain\Wallet
                alias: AppDomainWallet
            App\Domain\Transaction:
                dir: '%kernel.project_dir%/src/Domain/Transaction'
                is_bundle: false
                prefix: App\Domain\Transaction
                alias: AppDomainTransaction

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
