doctrine_migrations:
    migrations_paths:
        'App\Infrastructure\Persistence\Migrations': '%kernel.project_dir%/src/Infrastructure/Persistence/Migrations'
    enable_profiler: false
    transactional: false
