stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: feejkr/lb-finances:latest
  script:
    - composer install

tests:
  stage: test
  image: feejkr/lb-finances:latest
  before_script:
    - composer install
  script:
    - php bin/phpunit
  services:
    - mysql:8
