version: '3.7'

services:
  app:
    build:
      context: .
      target: app-dev
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      XDEBUG_MODE: "debug"
    volumes:
      - ./:/app
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./.docker/php/php.dev.ini:/usr/local/etc/php/conf.d/php.dev.ini:ro
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-8080}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-4430}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-4430}
        protocol: udp
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    environment:
      - MYSQL_ROOT_PASSWORD=finances
      - MYSQL_DATABASE=finances
    restart: always
    ports:
      - "3336:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD -e \"SELECT 1\" $$MYSQL_DATABASE &> /dev/null" ]
      interval: 30s
      timeout: 30s
      retries: 3
