name: Tests
on: [push]
jobs:
  tests:
    runs-on: self-hosted
    container:
      image: feejkr/lb-finances:latest
      volumes:
        - ./:/app
    steps:
      - name: Check phpstan
        run: /app/vendor/bin/phpstan -cphpstan.neon --ansi analyse
      - name: Check codestyle
        run: composer cs:check
