name: Tests
on: [push]
jobs:
  tests:
    runs-on: self-hosted
    container:
      image: feejkr/lb-finances:v1.0.0
      volumes:
        - .:/app
    steps:
      - name: Check phpstan
        run: ls -la
