name: Tests
on: [push]
jobs:
  tests:
    runs-on: self-hosted
    container:
      image: feejkr/lb-finances:latest
      volumes:
        - ./:/app
    steps:
      - run: ls -l 
      - run: ls -l /app
      - name: Check phpstan
        run: composer phpstan:check
      - name: Check codestyle
        run: composer cs:check
